### ISSUE TITLE
Font size on some tables will have to be reduced

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/pacific-cod-2018#101]
Examples include the decision tables. There may be an existing argument in those functions but there are other tables that also bleed over the right edge.

An example:

```r
existing_table_code %>%
 kableExtra::kable_styling(font_size = 8)
```

**Comment by robynforrest** [comment]
I think we can close this one. The decision tables do get close to the edge but they are still on the page! Chris has included code for some other tables (e.g., priors) that breaks the headers into two lines, so if this is still a problem we could do that

**Comment by robynforrest** [comment]
I broke the decision tables headers over two lines, fits nicely now
