### ISSUE TITLE
Correct prior for logM in Tables 7 and 14

### ISSUE THREAD

**Issue by robynforrest** [pbs-assess/pacific-cod-2018#105]
Mean of prior is ln(0.5) not ln(0.1)

**Comment by robynforrest** [comment]
Chris, please could you look at this one. The values are automated from the control file. I have looked at the control file and there is no 0.1 value there. Is it possible it is picking up the lower bound from the control file?

**Comment by cgrandin** [comment]
The control file has 0.1 in there.. I am looking at the 5ABCD base "0_1a_5ABCD_BASE_fix-localities" control file:

![image](https://user-images.githubusercontent.com/4551051/88627199-c5ab5800-d060-11ea-9b5b-a33112d5c202.png)

**Comment by robynforrest** [comment]
Fixed in commit https://github.com/pbs-assess/pacific-cod-2018/commit/f5785443c6c22c8c63297de8b80cd7c683268a34
