### ISSUE TITLE
Make tables accessible

### ISSUE THREAD

**Issue by robynforrest** [pbs-assess/pacific-cod-2018#110]
See instructions from Chris:
https://github.com/pbs-assess/csasdown/issues/134

**Comment by robynforrest** [comment]
Chris, would you have time to look at this?

**Comment by cgrandin** [comment]
I'm back today and I will have a look. Summer is over now

**Comment by cgrandin** [comment]
So I looked at the accessibility issues, and there aren't many major ones. I can do them quickly when the document is completely done and ready for submission. 

Trying to make the tables the way they are supposed to be, like in https://github.com/pbs-assess/csasdown/issues/134, is extremely tedious and I would like to show you through a Teams meeting where I share my screen. It involves editing every document tag one by one, for every table.

**Comment by seananderson** [comment]
So we don't need to make `longtable = TRUE` and `format = "latex"` throughout? And even with the perfect setup it still requires manual fiddling in whatever that PDF reader software is?

**Comment by cgrandin** [comment]
@seananderson Yes, the tables are all slightly wrong as far as the tagging is concerned but they are so close that I on second thought I think CSAP won't mind doing those edits manually themselves. I'm working on the ones that have major issues like this one (the rows are not separate tags): 

![image](https://user-images.githubusercontent.com/4551051/92622870-6903a580-f27a-11ea-9098-8cd9593ac6c8.png)

Table 11 is an issue, the second page are all <P> tags. I'll try to fix these ones with a code solution.

**Comment by cgrandin** [comment]
The worst part of this is that any code changes have to be duplicated in two versions and the tagging stuff has to be done twice

**Comment by seananderson** [comment]
Maybe we should create a checklist on the csasdown wiki. E.g., getting CSAP to agree that the table tagging looks reasonable would ideally happen before making a French copy or branch.

**Comment by cgrandin** [comment]
That's a good idea. I guess Arrowtooth will be the next test bed for this

**Comment by seananderson** [comment]
MP framework and yelloweye will be next for translation/accessibility...
plus a bunch of other reports from other people that I'm quickly losing
track of. Herring for one.

**Comment by cgrandin** [comment]
I think at this point I'll just wait and do the tagging once we are totally done with the docs. There are a couple tables which require a lot of tweaking with tags and it's too fiddly to do more than once.
