### ISSUE TITLE
Add French citation to p. ii

### ISSUE THREAD

**Issue by robynforrest** [pbs-assess/pacific-cod-2018#114]
p. ii.

Ann's comment "Add French citation. the same style as the English citation but italicized, with the page numbers updated to reflect the length of the French version"

Also need to add the English citation to the French version

**Comment by seananderson** [comment]
We started this doc in the early days of csasdown, but you can do this now like this:
https://github.com/pbs-assess/csasdown/blob/d873c4bf0524020295731998281bf1329dc8c0e0/inst/rmarkdown/templates/resdoc/skeleton/skeleton.Rmd#L17

**Comment by robynforrest** [comment]
Commit https://github.com/pbs-assess/pacific-cod-2018/commit/09e76fb18aa891268075bbbc9b8fa6c6014805ff

Will need to do a last minute check to make sure final page numbers are correct
