### ISSUE TITLE
Look at CSAS issues in English Doc

### ISSUE THREAD

**Issue by robynforrest** [pbs-assess/pacific-cod-2018#126]
I think these are all csasdown issues:

- [x] Underline hyperlink on foreword page

- [x] Font of table of contents? – "Ottawa noted the TOC font looked off, but I let them know the font was the same used throughout the document and maybe it was the formatting that made it look a bit different. If you are able to increase the space slightly between headings and increase the tab leaders (number of dots between text and page number) that would be great. This isn’t a deal breaker. I put a screen shot below of what our TOCs usually look like in terms of leaders and spacing **[posted in Slack]**. (This one shows level 3 headings but yours is fine with two levels! The spacing between the section number  and section title – eg. 1  INTRODUCTION - doesn’t need to look like the one below either)"

- [x] Can the References heading be numbered?

- [x] Should Equation numbers be in parentheses? Note that all of the "extra" parentheses highlighted by Ann are not extra, but due to the numbers being in parentheses, e.g. (Eq. (D.29)). I'm not sure if this is actually an issue.

**Comment by cgrandin** [comment]
References section now numbered, see https://github.com/pbs-assess/csasdown/commit/c48b16c5e006349d61533d51a3dfe317ad53ef5f

**Comment by cgrandin** [comment]
I compared the TOC from an accepted salmon resdoc: http://www.dfo-mpo.gc.ca/csas-sccs/Publications/ResDocs-DocRech/2020/2020_035-eng.pdf

![image](https://user-images.githubusercontent.com/4551051/94472526-bc815900-017f-11eb-9c05-1d9ed2ac67e0.png)

To the current Pcod one:

![image](https://user-images.githubusercontent.com/4551051/94472676-f05c7e80-017f-11eb-845b-9115449bfb57.png)

The spacing between the entries is different and ours is in all caps. Maybe that's why they say it "looks different"

**Comment by cgrandin** [comment]
Note that they have accepted many research docs from us with this format

**Comment by robynforrest** [comment]
Note Ann's comment above that ours is fine with only two levels of headings. See her note also that this isn't a deal-breaker

**Comment by cgrandin** [comment]
Dot spacing done in https://github.com/pbs-assess/csasdown/commit/ec2f4402b6bc06c752f94e97857a1f76d2766295

**Comment by cgrandin** [comment]
`Vertical spacing done in 05a6f3cc2b0529e122c0d4eb4dd5046064519460.

I think this is very close to what they want so I'll check the box and leave to @robynforrest to close this

**Comment by cgrandin** [comment]
![image](https://user-images.githubusercontent.com/4551051/94484099-c2336a80-0190-11eb-820f-b905bed7386e.png)
